#!/bin/bash

#docker login --username=_ --password="$HEROKU_API_KEY" registry.heroku.com
#docker build -t registry.heroku.com/tiltbot2/web .
#docker push registry.heroku.com/tiltbot2/web

heroku container:login
docker login --username=_ --password="$HEROKU_API_KEY" registry.heroku.com
docker build -t registry.heroku.com/tiltbot2/web .
heroku container:push web
heroku container:release web
