#!/bin/bash

docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD" registry.heroku.com
docker build -t registry.heroku.com/tiltbot2/web .
docker push registry.heroku.com/tiltbot2/web
